### ISSUE TITLE
Automate the SampleApp.war build

### ISSUE THREAD

**Issue by ChamathNS** [wso2-extensions/identity-agent-sso#71]
**Description:**
Currently, the SampleApp.war file in the resources/SampleApp/target directory has to be manually uploaded to the release artifacts of the repository. This task should be automated going forward.

**Related Issues:**
https://github.com/wso2/product-is/issues/8956
https://github.com/wso2/product-is/issues/9115

**Comment by gayashanbc** [comment]
Closing as this was resolved in https://github.com/asgardio/asgardio-tomcat-saml-agent.
