### ISSUE TITLE
Incoporating steps for user creation and service provider claim configuration

### ISSUE THREAD

**Issue by ChamathNS** [wso2-extensions/identity-agent-sso#73]
**Description:**
In the README.md, under the "Trying out the sample" section, the steps for user creation and service provider claim configuration are not included. Going forward, we would need to provide the users with the necessary steps (possibly via a shell script) to create the users and configure the service provider claims.

**Comment by ChamathNS** [comment]
Service provider claim configuration has been added to the README.md with https://github.com/wso2-extensions/identity-agent-sso/pull/74

**Comment by gayashanbc** [comment]
This issue is tracked from https://github.com/asgardio/asgardio-tomcat-oidc-agent/issues/3
